### ISSUE TITLE
Conditionally show email "variable/tokens/!!etc!!" based on which email template is shown.

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/pmpro-email-templates#12] opened 2017-11-21 17:17 UTC
This may not be easy. An alternative is to just warn people that not all variables are available for every template.

**Comment by kimcoleman** [comment] 2018-11-26 17:05
Duplicate of https://github.com/strangerstudios/pmpro-email-templates/issues/20

**Closed by kimcoleman** 2018-11-26 17:05 UTC
